name: google_api_headers
description: Patched version of google_api_headers with namespace support for Gradle 8+
version: 2.0.2+patched
homepage: https://github.com/YOUR_USERNAME/google_api_headers_patched

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  http: ^1.2.1
